// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_CNR83O7CtTGcNK8CDSKlxowtDZN3hs',
    appId: '1:970082657610:web:55250d53c0b45364ba0db3',
    messagingSenderId: '970082657610',
    projectId: 'work-it-eb8a3',
    authDomain: 'work-it-eb8a3.firebaseapp.com',
    storageBucket: 'work-it-eb8a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgnk4oIId8GB3WUYvLqL9JHKjxOUrF-jE',
    appId: '1:970082657610:android:9955b10e3a63c1a4ba0db3',
    messagingSenderId: '970082657610',
    projectId: 'work-it-eb8a3',
    storageBucket: 'work-it-eb8a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMl86mdjkZThlxRz8LNsG7W6vBV90csI',
    appId: '1:970082657610:ios:bc82c0b2cff58f18ba0db3',
    messagingSenderId: '970082657610',
    projectId: 'work-it-eb8a3',
    storageBucket: 'work-it-eb8a3.appspot.com',
    androidClientId: '970082657610-g7g8c27j0e1aonnejiv9q6nsjj0d8p47.apps.googleusercontent.com',
    iosClientId: '970082657610-4v6hkmofrg15qmppej5ksfsgrgn2hl78.apps.googleusercontent.com',
    iosBundleId: 'com.example.workit',
  );
}
